# Listen di port standar
listener 1883 0.0.0.0

# Listen untuk WebSockets (jika frontend butuh)
listener 9001 0.0.0.0
protocol websockets

# Izinkan koneksi tanpa username/password (untuk tahap development)
allow_anonymous true

# Lokasi penyimpanan data
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log