server {
    listen 80;
    server_name _; # Mengizinkan akses dari IP mana pun

    # Akses Frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy ke API Backend Node.js
    location /api/ {
        proxy_pass http://backend:3000/; # Sesuaikan dengan port app.listen di Node.js Anda
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}